import { BaseAgent } from './BaseAgent'
import { ProjectWorkspace } from '@/services/workspace/ProjectWorkspace'
import { AgentOutput, ProjectContext } from '@/types/orchestrator'

export interface BackendDeveloperContext {
  projectId: string
  userRequest: string
  workspace: ProjectWorkspace
  architecture?: any
}

export interface BackendDeveloperOutput {
  filesCreated: string[]
  filesModified: string[]
  cost: number
  duration: number
}

export class BackendDeveloper extends BaseAgent {
  agentType = 'BackendDeveloper' as const

  private workspace: ProjectWorkspace
  private userRequest: string
  private architecture?: any

  constructor(context: BackendDeveloperContext) {
    // Create a minimal ProjectContext for BaseAgent
    const projectContext: ProjectContext = {
      state: {
        userRequest: context.userRequest,
        userId: 'test-user',
        organizationId: 'test-org',
        projectId: context.projectId,
        projectName: context.projectId,
        createdAt: new Date().toISOString(),
        agentsSpawned: [],
        agentOutputs: {},
        errors: [],
        retryCount: 0,
      },
      organizationId: 'test-org',
      userId: 'test-user',
      costOptimizerUrl: process.env.COST_OPTIMIZER_URL || 'http://localhost:3001',
      costOptimizerApiKey: process.env.COST_OPTIMIZER_API_KEY || 'test-key',
    }

    super('BackendDeveloper', projectContext)
    this.workspace = context.workspace
    this.userRequest = context.userRequest
    this.architecture = context.architecture
  }

  async execute(): Promise<AgentOutput> {
    const startTime = Date.now()

    try {
      // TODO: Load skills (test-driven-development, api-design-patterns, security-best-practices)
      // TODO: Use MCP tools (context7, sequential-thinking, supabase)

      // For MVP: Generate simple API file structure
      const prompt = this.buildPrompt()
      const response = await this.think({ prompt, complexity: 'simple' })

      // Parse response and generate files
      const files = await this.generateFiles(response)

      this.output.duration = Date.now() - startTime

      return this.getOutput()
    } catch (error) {
      console.error('[BackendDeveloper] Error:', error)
      this.addError(`BackendDeveloper execution failed: ${error}`)
      this.output.duration = Date.now() - startTime
      return this.getOutput()
    }
  }

  private buildPrompt(): string {
    return `You are a backend developer agent. Generate TypeScript files for the following request:

User Request: ${this.userRequest}

${this.architecture ? `Architecture Context:\n${JSON.stringify(this.architecture, null, 2)}\n` : ''}

Generate a simple API structure with:
1. API route file (app/api/[resource]/route.ts)
2. Service layer file (src/services/[resource]Service.ts)
3. Type definitions (src/types/[resource].ts)

Return a JSON array of files:
[
  {
    "path": "app/api/todos/route.ts",
    "content": "import { NextRequest, NextResponse } from 'next/server'..."
  },
  {
    "path": "src/services/todoService.ts",
    "content": "export class TodoService { ... }"
  }
]

Keep it simple and focused. Use Next.js 15 patterns.`
  }

  private async generateFiles(response: string): Promise<string[]> {
    try {
      // Try to parse JSON response
      const files = JSON.parse(response)
      const createdFiles: string[] = []

      for (const file of files) {
        await this.workspace.writeFile(file.path, file.content)
        createdFiles.push(file.path)

        // Track file creation using BaseAgent method
        this.addFileCreated(file.path)
      }

      return createdFiles
    } catch (error) {
      // If JSON parsing fails, create a single example file
      console.warn('[BackendDeveloper] Failed to parse response, creating example file')

      const exampleFile = 'src/example-generated.ts'
      await this.workspace.writeFile(exampleFile, `// Generated by BackendDeveloper\n// Request: ${this.userRequest}\n\nexport const placeholder = true;`)

      this.addFileCreated(exampleFile)
      return [exampleFile]
    }
  }
}
