/**
 * Frontend Developer Agent
 *
 * Generates React/Next.js components with TypeScript, Tailwind CSS,
 * and optional UI library integration (shadcn/ui). Follows BaseAgent
 * pattern with cost-optimizer integration for efficient AI usage.
 *
 * @module agents/FrontendDeveloper
 */

import { BaseAgent } from './BaseAgent'
import { ProjectWorkspace } from '@/services/workspace/ProjectWorkspace'
import { AgentOutput, ProjectContext } from '@/types/orchestrator'

export interface FrontendDeveloperContext {
  projectId: string
  userRequest: string
  workspace: ProjectWorkspace
  projectContext: {
    framework: string
    styling: string
    uiLibrary?: string
  }
  architecture?: any
}

export class FrontendDeveloper extends BaseAgent {
  agentType = 'FrontendDeveloper' as const

  private workspace: ProjectWorkspace
  private userRequest: string
  private frontendContext: {
    framework: string
    styling: string
    uiLibrary?: string
  }
  private architecture?: any

  constructor(context: FrontendDeveloperContext) {
    // Create a minimal ProjectContext for BaseAgent
    const projectContext: ProjectContext = {
      state: {
        userRequest: context.userRequest,
        userId: 'test-user',
        organizationId: 'test-org',
        projectId: context.projectId,
        projectName: context.projectId,
        createdAt: new Date().toISOString(),
        agentsSpawned: [],
        agentOutputs: {},
        errors: [],
        retryCount: 0,
      },
      organizationId: 'test-org',
      userId: 'test-user',
      costOptimizerUrl: process.env.COST_OPTIMIZER_URL || 'http://localhost:3001',
      costOptimizerApiKey: process.env.COST_OPTIMIZER_API_KEY || 'test-key',
    }

    super('FrontendDeveloper', projectContext)
    this.workspace = context.workspace
    this.userRequest = context.userRequest
    this.frontendContext = context.projectContext
    this.architecture = context.architecture
  }

  async execute(): Promise<AgentOutput> {
    const startTime = Date.now()

    try {
      console.log('🎨 FrontendDeveloper: Generating React components...')

      // Build prompt for component generation
      const prompt = this.buildPrompt()
      const response = await this.think({ prompt, complexity: 'medium' })

      // Parse response and generate files
      const files = await this.generateFiles(response)

      console.log(`✅ FrontendDeveloper: Generated ${files.length} component files`)

      this.output.duration = Date.now() - startTime

      return this.getOutput()
    } catch (error) {
      console.error('[FrontendDeveloper] Error:', error)
      this.addError(`FrontendDeveloper execution failed: ${error}`)
      this.output.duration = Date.now() - startTime
      return this.getOutput()
    }
  }

  private buildPrompt(): string {
    const { framework, styling, uiLibrary } = this.frontendContext

    return `You are an expert frontend developer. Generate React/Next.js components based on the following requirements:

**User Request:** ${this.userRequest}

**Project Context:**
- Framework: ${framework}
- Styling: ${styling}
${uiLibrary ? `- UI Library: ${uiLibrary}` : ''}

${this.architecture ? `**Architecture Context:**\n${JSON.stringify(this.architecture, null, 2)}\n` : ''}

**Requirements:**
1. Use TypeScript with strict types
2. Follow React best practices (hooks, functional components)
3. Use ${styling} for styling
${uiLibrary ? `4. Use ${uiLibrary} components where appropriate` : ''}
4. Include proper accessibility (ARIA labels, semantic HTML)
5. Add JSDoc comments for complex logic
6. Keep components focused (single responsibility)

**Output Format:**
Return a JSON array of component files:
[
  {
    "path": "src/components/category/ComponentName.tsx",
    "content": "// Full component code here..."
  }
]

Generate production-ready code with proper error handling and type safety.`
  }

  private async generateFiles(response: string): Promise<string[]> {
    try {
      // Try to parse JSON response
      const files = JSON.parse(response)
      const createdFiles: string[] = []

      for (const file of files) {
        await this.workspace.writeFile(file.path, file.content)
        createdFiles.push(file.path)

        // Track file creation using BaseAgent method
        this.addFileCreated(file.path)
      }

      return createdFiles
    } catch (error) {
      // If JSON parsing fails, create a single example file
      console.warn('[FrontendDeveloper] Failed to parse response, creating example file')
      this.addWarning('Failed to parse AI response, created example file instead')

      const exampleFile = 'src/components/ExampleComponent.tsx'
      const exampleContent = `// Generated by FrontendDeveloper
// Request: ${this.userRequest}

export function ExampleComponent() {
  return (
    <div className="p-4">
      <h2>Example Component</h2>
      <p>Generated based on: {${JSON.stringify(this.userRequest)}}</p>
    </div>
  )
}
`

      await this.workspace.writeFile(exampleFile, exampleContent)
      this.addFileCreated(exampleFile)
      return [exampleFile]
    }
  }
}
