/**
 * Tester Agent
 *
 * Generates comprehensive test files including Jest unit tests and
 * Playwright E2E tests. Follows BaseAgent pattern with cost-optimizer
 * integration for efficient AI usage.
 *
 * @module agents/Tester
 */

import { BaseAgent } from './BaseAgent'
import { ProjectWorkspace } from '@/services/workspace/ProjectWorkspace'
import { AgentOutput, ProjectContext } from '@/types/orchestrator'

export interface TesterContext {
  projectId: string
  userRequest: string
  workspace: ProjectWorkspace
  codeToTest: string
  testType: 'unit' | 'e2e'
}

export class Tester extends BaseAgent {
  agentType = 'Tester' as const

  private workspace: ProjectWorkspace
  private userRequest: string
  private codeToTest: string
  private testType: 'unit' | 'e2e'

  constructor(context: TesterContext) {
    // Create a minimal ProjectContext for BaseAgent
    const projectContext: ProjectContext = {
      state: {
        userRequest: context.userRequest,
        userId: 'test-user',
        organizationId: 'test-org',
        projectId: context.projectId,
        projectName: context.projectId,
        createdAt: new Date().toISOString(),
        agentsSpawned: [],
        agentOutputs: {},
        errors: [],
        retryCount: 0,
      },
      organizationId: 'test-org',
      userId: 'test-user',
      costOptimizerUrl: process.env.COST_OPTIMIZER_URL || 'http://localhost:3001',
      costOptimizerApiKey: process.env.COST_OPTIMIZER_API_KEY || 'test-key',
    }

    super('Tester', projectContext)
    this.workspace = context.workspace
    this.userRequest = context.userRequest
    this.codeToTest = context.codeToTest
    this.testType = context.testType
  }

  async execute(): Promise<AgentOutput> {
    const startTime = Date.now()

    try {
      console.log(`🧪 Tester: Generating ${this.testType} tests...`)

      // Build prompt for test generation
      const prompt = this.buildPrompt()
      const response = await this.think({ prompt, complexity: 'medium' })

      // Parse response and generate test files
      const files = await this.generateFiles(response)

      console.log(`✅ Tester: Generated ${files.length} test files`)

      this.output.duration = Date.now() - startTime

      return this.getOutput()
    } catch (error) {
      console.error('[Tester] Error:', error)
      this.addError(`Tester execution failed: ${error}`)
      this.output.duration = Date.now() - startTime
      return this.getOutput()
    }
  }

  private buildPrompt(): string {
    if (this.testType === 'unit') {
      return `You are an expert test engineer. Generate Jest unit tests for the following code:

**User Request:** ${this.userRequest}

**Code to Test:**
\`\`\`typescript
${this.codeToTest}
\`\`\`

**Requirements:**
1. Use Jest + React Testing Library
2. Test all user interactions
3. Test edge cases and error handling
4. Use proper test structure (describe, it, expect)
5. Mock external dependencies
6. Test accessibility features
7. Aim for 80%+ code coverage

**Output Format:**
Return a JSON array of test files:
[
  {
    "path": "tests/components/ComponentName.test.tsx",
    "content": "// Full test code here..."
  }
]

Generate production-ready tests with comprehensive coverage.`
    } else {
      return `You are an expert test engineer. Generate Playwright E2E tests for the following scenario:

**User Request:** ${this.userRequest}

**Requirements:**
1. Use Playwright test framework
2. Test complete user workflows
3. Include proper test fixtures
4. Test responsive design (mobile + desktop)
5. Test accessibility
6. Handle loading states and async operations
7. Include meaningful assertions

**Output Format:**
Return a JSON array of test files:
[
  {
    "path": "tests/e2e/feature-name.spec.ts",
    "content": "// Full E2E test code here..."
  }
]

Generate production-ready E2E tests that verify end-to-end user flows.`
    }
  }

  private async generateFiles(response: string): Promise<string[]> {
    try {
      // Try to parse JSON response
      const files = JSON.parse(response)
      const createdFiles: string[] = []

      for (const file of files) {
        await this.workspace.writeFile(file.path, file.content)
        createdFiles.push(file.path)

        // Track file creation using BaseAgent method
        this.addFileCreated(file.path)
      }

      return createdFiles
    } catch (error) {
      // If JSON parsing fails, create a single example test file
      console.warn('[Tester] Failed to parse response, creating example test file')
      this.addWarning('Failed to parse AI response, created example test file instead')

      const exampleFile =
        this.testType === 'unit'
          ? 'tests/components/ExampleComponent.test.tsx'
          : 'tests/e2e/example-flow.spec.ts'

      const exampleContent =
        this.testType === 'unit'
          ? `// Generated by Tester
// Request: ${this.userRequest}
import { render, screen } from '@testing-library/react'

describe('Example Test', () => {
  it('should be replaced with actual tests', () => {
    expect(true).toBe(true)
  })
})
`
          : `// Generated by Tester
// Request: ${this.userRequest}
import { test, expect } from '@playwright/test'

test.describe('Example E2E Test', () => {
  test('should be replaced with actual tests', async ({ page }) => {
    expect(true).toBe(true)
  })
})
`

      await this.workspace.writeFile(exampleFile, exampleContent)
      this.addFileCreated(exampleFile)
      return [exampleFile]
    }
  }
}
