"""
Pydantic schemas for validating orchestrator plans and agent outputs
Using Pydantic v2 for robust JSON schema validation
"""

from pydantic import BaseModel, Field
from typing import List, Literal, Optional, Dict, Any
from datetime import datetime


class GeneratedFile(BaseModel):
    """Individual file generated by an agent"""
    path: str = Field(..., description="File path relative to project root")
    content: str = Field(..., description="File content")
    description: str = Field(..., description="What this file does")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "path": "src/api/users.py",
                    "content": "from fastapi import APIRouter\n\nrouter = APIRouter()\n\n@router.get('/users')\nasync def list_users():\n    return {'users': []}",
                    "description": "User API endpoints"
                }
            ]
        }
    }


class AgentTask(BaseModel):
    """Task assigned to an agent"""
    agent_type: Literal['CodeArchitect', 'BackendDeveloper', 'FrontendDeveloper', 'Tester', 'DevOpsEngineer'] = Field(
        ..., description="Type of agent to execute this task"
    )
    description: str = Field(..., description="Detailed task description")
    dependencies: List[str] = Field(default_factory=list, description="List of task IDs this depends on")
    estimated_duration: int = Field(..., description="Estimated time in minutes", gt=0)

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "agent_type": "CodeArchitect",
                    "description": "Design system architecture for user management",
                    "dependencies": [],
                    "estimated_duration": 30
                }
            ]
        }
    }


class OrchestratorPlan(BaseModel):
    """Complete orchestration plan for a project"""
    project_name: str = Field(..., description="Name of the project", min_length=1)
    language: Literal['typescript', 'python', 'go', 'rust'] = Field(
        ..., description="Primary programming language"
    )
    framework: str = Field(..., description="Framework to use (e.g., fastapi, nextjs)", min_length=1)
    tasks: List[AgentTask] = Field(..., description="List of tasks to execute", min_length=1)
    total_estimated_time: int = Field(..., description="Total time in minutes", gt=0)
    created_at: Optional[datetime] = Field(default_factory=datetime.now, description="Plan creation timestamp")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "project_name": "user-management-api",
                    "language": "python",
                    "framework": "fastapi",
                    "tasks": [
                        {
                            "agent_type": "CodeArchitect",
                            "description": "Design architecture",
                            "dependencies": [],
                            "estimated_duration": 30
                        },
                        {
                            "agent_type": "BackendDeveloper",
                            "description": "Implement API endpoints",
                            "dependencies": ["CodeArchitect"],
                            "estimated_duration": 60
                        }
                    ],
                    "total_estimated_time": 90
                }
            ]
        }
    }


class AgentOutput(BaseModel):
    """Output from a single agent"""
    agent_type: str = Field(..., description="Type of agent that generated this output")
    files_created: List[GeneratedFile] = Field(..., description="Files created by the agent")
    files_modified: List[GeneratedFile] = Field(default_factory=list, description="Files modified by the agent")
    warnings: List[str] = Field(default_factory=list, description="Non-critical warnings")
    errors: List[str] = Field(default_factory=list, description="Critical errors encountered")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Additional metadata")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "agent_type": "BackendDeveloper",
                    "files_created": [
                        {
                            "path": "src/api/users.py",
                            "content": "from fastapi import APIRouter...",
                            "description": "User API endpoints"
                        }
                    ],
                    "files_modified": [],
                    "warnings": ["Consider adding rate limiting"],
                    "errors": [],
                    "metadata": {
                        "duration_seconds": 45,
                        "model_used": "claude-3-5-sonnet"
                    }
                }
            ]
        }
    }


class ValidationResponse(BaseModel):
    """Response from validation endpoint"""
    valid: bool = Field(..., description="Whether the data passed validation")
    errors: List[str] = Field(default_factory=list, description="Validation errors if any")
    validated_data: Optional[Dict[str, Any]] = Field(default=None, description="Validated and normalized data")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "valid": True,
                    "errors": [],
                    "validated_data": {"project_name": "test-project"}
                },
                {
                    "valid": False,
                    "errors": ["Field required: 'language'"],
                    "validated_data": None
                }
            ]
        }
    }
